metrodroid/metrodroid

- src/main/java/au/id/micolous/farebot/transit/orca/OrcaTransitData.java
- src/main/java/au/id/micolous/farebot/transit/orca/OrcaTrip.java
Rebase of cyberkitsune/add-orca-et (codebutler/farebot#96) to micolous/farebot.
> Add name and authority code for Everett Transit. (ORCA)

- src/main/java/au/id/micolous/metrodroid/MetrodroidApplication.java
- src/main/java/com/codebutler/farebot/card/classic/ClassicCard.java
- src/main/java/com/codebutler/farebot/ui/NumberPickerPreference.java
- src/main/res/values/strings.xml
- src/main/res/xml/prefs.xml
Some cards are unreliable, and will return authentication failures, even when the key is correct.  Thick phone cases also don't help here.
This can lead someone to believe that they have entered their key incorrectly.
Lets be a bit more aggressive and try each key multiple times before actually giving up.
TODO: Make this retry value configurable.
> In progress: Mifare Classic auth retry logic

- src/main/java/com/codebutler/farebot/card/classic/ClassicCard.java
- src/main/java/com/codebutler/farebot/fragment/CardSubscriptionsFragment.java
- src/main/java/com/codebutler/farebot/transit/nextfare/NextfareRefill.java
- src/main/java/com/codebutler/farebot/transit/nextfare/NextfareSubscription.java
- src/main/java/com/codebutler/farebot/transit/nextfare/NextfareTransitData.java
- src/main/java/com/codebutler/farebot/transit/nextfare/NextfareTrip.java
- src/main/java/com/codebutler/farebot/transit/nextfare/NextfareUtil.java
- src/main/java/com/codebutler/farebot/transit/nextfare/README.md
- src/main/java/com/codebutler/farebot/transit/nextfare/record/NextfareBalanceRecord.java
- src/main/java/com/codebutler/farebot/transit/nextfare/record/NextfareRecord.java
- src/main/java/com/codebutler/farebot/transit/nextfare/record/NextfareTapRecord.java
- src/main/java/com/codebutler/farebot/transit/nextfare/record/NextfareTopupRecord.java
- src/main/java/com/codebutler/farebot/transit/nextfare/record/NextfareTravelPassRecord.java
- src/main/java/com/codebutler/farebot/transit/seq_go/SeqGoFareCalculator.java
- src/main/java/com/codebutler/farebot/transit/seq_go/SeqGoRefill.java
- src/main/java/com/codebutler/farebot/transit/seq_go/SeqGoTransitData.java
- src/main/java/com/codebutler/farebot/transit/seq_go/SeqGoTrip.java
- src/main/java/com/codebutler/farebot/transit/seq_go/SeqGoUtil.java
- src/main/java/com/codebutler/farebot/util/Utils.java
- src/main/res/values/strings.xml
- src/main/res/xml/prefs.xml
This refactors the `seq_go` reader into a generic `nextfare` reader.
This allows basic reading of the LAX TAP card.
> In progress: Nextfare refactor (#17)

- src/main/java/au/id/micolous/metrodroid/activity/AdvancedCardInfoActivity.java
- src/main/java/au/id/micolous/metrodroid/fragment/CardsFragment.java
Current code exports cards as text/plain but looks for text/xml for
importing. So export as text/xml and accept both text/plain and text/xml for
importing.
> Fix MIME types.

- src/main/java/au/id/micolous/metrodroid/activity/CardInfoActivity.java
Serial is often pretty log and is cut, this will give it more room
This simple idea is copied from farebot
> Move serial to subtitle

- src/main/java/au/id/micolous/metrodroid/transit/clipper/ClipperRefill.java
Clipper crashes due to bad cast to comparable. Fix it
> Fix clipper crash

- src/main/java/au/id/micolous/metrodroid/transit/orca/MergedOrcaTrip.java
- src/main/java/au/id/micolous/metrodroid/transit/orca/OrcaTrip.java
Change from CompatTrip to Trip and hence Calendar. Fixes the problem of showing local time in Orca
> Move Orca to Calendar

- src/main/java/au/id/micolous/metrodroid/activity/CardInfoActivity.java
- src/main/java/au/id/micolous/metrodroid/activity/MainActivity.java
- src/main/java/au/id/micolous/metrodroid/card/Card.java
- src/main/java/au/id/micolous/metrodroid/card/ultralight/UltralightCard.java
- src/main/java/au/id/micolous/metrodroid/card/ultralight/UltralightProtocol.java
- src/main/java/au/id/micolous/metrodroid/fragment/BlankCardFragment.java
- src/main/java/au/id/micolous/metrodroid/transit/unknown/BlankUltralightTransitData.java
- src/main/java/au/id/micolous/metrodroid/util/Utils.java
- src/main/res/layout/fragment_blank_card.xml
- src/main/res/values/strings.xml
Several fixes to better support ultralight tags
> Ultralight

- build.gradle
- src/main/java/au/id/micolous/metrodroid/activity/SupportedCardsActivity.java
- src/main/res/drawable/ic_lock_yellow_24dp.xml
- src/main/res/layout/activity_supported_cards.xml
- src/main/res/layout/supported_card.xml
Serial is often pretty log and is cut, this will give it more room
This simple idea is copied from farebot
> Import supported cards view from farebot

- src/main/java/au/id/micolous/metrodroid/util/TripObfuscator.java
It has quite some code dealing e.g. with UNIX timestamps whicha aren't used
anymore. Kill them.
> Cleanup TripObfuscator.

- src/main/java/au/id/micolous/metrodroid/util/StationTableReader.java
This is very helpful to avoid inline databases in Opus and Shenzhen Tong.
> Support retrieving operator and line in StationTableReader.

- src/main/java/au/id/micolous/metrodroid/card/calypso/CalypsoApplication.java
- src/main/java/au/id/micolous/metrodroid/transit/CardInfo.java
- src/main/java/au/id/micolous/metrodroid/transit/ravkav/RavKavTransitData.java
- src/main/java/au/id/micolous/metrodroid/transit/ravkav/RavKavTrip.java
- src/main/res/values/strings.xml
This adds support for Israeli Rav-Kav cards.
> RavKav support

- src/main/java/au/id/micolous/metrodroid/transit/clipper/ClipperData.java
- src/main/java/au/id/micolous/metrodroid/transit/clipper/ClipperTrip.java
- src/main/java/au/id/micolous/metrodroid/transit/orca/OrcaTrip.java
Import Orca and Clipper updates from Farebot
> Farebot data

- src/main/java/au/id/micolous/metrodroid/MetrodroidApplication.java
- src/main/res/drawable/ic_add_black_24dp.xml
- src/main/res/drawable/ic_transaction_banned_32dp.xml
- src/main/res/drawable/ic_transaction_bus_32dp.xml
- src/main/res/drawable/ic_transaction_ferry_32dp.xml
- src/main/res/drawable/ic_transaction_metro_32dp.xml
- src/main/res/drawable/ic_transaction_pos_32dp.xml
- src/main/res/drawable/ic_transaction_train_32dp.xml
- src/main/res/drawable/ic_transaction_tram_32dp.xml
- src/main/res/drawable/ic_transaction_tvm_32dp.xml
- src/main/res/drawable/ic_transaction_unknown_32dp.xml
- src/main/res/drawable/ic_transaction_vend_32dp.xml
- src/main/res/values/strings.xml
- src/main/res/values/themes.xml
Great thanks to Eric Butler for this look.
> Import the theme from FareBot.

- src/main/java/au/id/micolous/metrodroid/activity/TripMapActivity.java
- src/main/java/au/id/micolous/metrodroid/fragment/CardTripsFragment.java
On API 16 and earlier having a javascript interface creates a security problem.
Just disable map for API < 17.
> Disable map for API < 17.

- src/main/java/au/id/micolous/metrodroid/card/desfire/DesfireProtocol.java
In some commands it means that sender needs to send additional data
and not that there is additional data to fetch
This is a preparation for unlocking cards.
> Change desfire handling of AF command

- src/androidTest/java/au/id/micolous/metrodroid/test/ClipperTest.java
- src/main/java/au/id/micolous/metrodroid/transit/clipper/ClipperTransitData.java
While on it change bitmasking to Utils.byteArrayToInt for reading balance
> Read clipper expiry

- src/main/java/au/id/micolous/metrodroid/card/iso7816/ISO7816Card.java
- src/main/java/au/id/micolous/metrodroid/card/tmoney/TMoneyCard.java
- src/main/java/au/id/micolous/metrodroid/transit/CardInfo.java
- src/main/java/au/id/micolous/metrodroid/transit/TransitCurrency.java
- src/main/java/au/id/micolous/metrodroid/transit/tmoney/TMoneyTransitData.java
- src/main/java/au/id/micolous/metrodroid/transit/tmoney/TMoneyTrip.java
- src/main/java/au/id/micolous/metrodroid/xml/ISO7816Converter.java
- src/main/res/values/strings.xml
Trip entry seems to have some kind of terminal serial number but I'm not
sure how they map to transport. So for now all transactions are "unknown"
> Add support for T-Money card

- src/main/java/au/id/micolous/metrodroid/transit/ravkav/RavKavTransitData.java
Turns out I was matching on part of manufacture date. Match on ticketing
environment instead.
> Fix Rav-Kav detection

- src/main/java/au/id/micolous/metrodroid/transit/nextfare/record/NextfareBalanceRecord.java
It's not entirely clear if the code is meant for 2-complement or sign flag.
Current code would result in huge negative balances, so just change
it to sign flag.
> nextfare: Add missing and in negative balance

- src/main/java/au/id/micolous/metrodroid/transit/suica/SuicaDBUtil.java
- src/main/java/au/id/micolous/metrodroid/transit/suica/SuicaTransitData.java
- src/main/java/au/id/micolous/metrodroid/transit/suica/SuicaTrip.java
* Pull time from tap log.
* Pass human readable ID to STR.
* Remove bunch of fields used only in constructor in SuicaTrip
> Suica improvements.

- src/main/java/au/id/micolous/metrodroid/card/desfire/DesfireCard.java
- src/main/java/au/id/micolous/metrodroid/transit/CardInfo.java
- src/main/java/au/id/micolous/metrodroid/transit/istanbulkart/IstanbulKartTransitData.java
- src/main/res/values/strings.xml
Reading other data needs keys. So it's basically like Myki.
> Implement serial number reading for IstanbulKart.

- src/main/java/au/id/micolous/metrodroid/card/calypso/CalypsoApplication.java
- src/main/java/au/id/micolous/metrodroid/card/iso7816/ISO7816Application.java
- src/main/java/au/id/micolous/metrodroid/card/iso7816/ISO7816Card.java
They're way nicer that numerical IDs.
> Show file name for Calypso in raw view.

- src/main/java/au/id/micolous/metrodroid/card/cepas/CEPASApplication.java
- src/main/java/au/id/micolous/metrodroid/card/cepas/CEPASProtocol.java
> Make CEPAS select match old code.

- src/main/java/au/id/micolous/metrodroid/transit/charlie/CharlieCardTransitData.java
* fix epoch
* fix expiry date
* skip second serial if it's not there
> charliecard fixes

- src/main/java/au/id/micolous/metrodroid/activity/AddKeyActivity.java
- src/main/java/au/id/micolous/metrodroid/card/cepas/CEPASApplication.java
- src/main/java/au/id/micolous/metrodroid/card/classic/ClassicCard.java
- src/main/java/au/id/micolous/metrodroid/card/desfire/DesfireApplication.java
- src/main/java/au/id/micolous/metrodroid/card/desfire/DesfireAuthLog.java
- src/main/java/au/id/micolous/metrodroid/card/felica/FelicaCard.java
- src/main/java/au/id/micolous/metrodroid/card/iso7816/ISO7816Card.java
- src/main/java/au/id/micolous/metrodroid/card/newshenzhen/NewShenzhenCard.java
- src/main/java/au/id/micolous/metrodroid/card/tmoney/TMoneyCard.java
- src/main/java/au/id/micolous/metrodroid/card/ultralight/UltralightCard.java
- src/main/java/au/id/micolous/metrodroid/transit/nextfare/NextfareTransitData.java
- src/main/java/au/id/micolous/metrodroid/ui/ListItemRecursive.java
- src/main/java/au/id/micolous/metrodroid/util/Utils.java
* Use monospace font
* Break down hex in 4-byte groups
* Break down hex in 16-byte lines
* Add hex address
* Break down record files on Desfire into individual records being careful
to include all bytes even on malformed files
> Improve readability for raw tabs

- src/main/java/au/id/micolous/metrodroid/card/desfire/DesfireCard.java
- src/main/java/au/id/micolous/metrodroid/transit/CardInfo.java
- src/main/java/au/id/micolous/metrodroid/transit/trimethop/TrimetHopTransitData.java
- src/main/res/values/strings.xml
Card has almost no data on it, so just parsing whatever is there.
> Trimet Hop parser

- src/main/java/au/id/micolous/metrodroid/card/classic/ClassicCard.java
- src/main/java/au/id/micolous/metrodroid/key/ClassicCardKeys.java
- src/main/java/au/id/micolous/metrodroid/key/ClassicStaticKeys.java
- src/main/java/au/id/micolous/metrodroid/provider/CardKeyProvider.java
Currently keys are completely broken due to provider using from component and other reasons. This is fix
> Fixes for classic card

- build.gradle
This way you don't lose entire DB when running tests
> Change test package name

- src/main/java/au/id/micolous/metrodroid/card/desfire/DesfireCard.java
They all are either hex of BCD
> Show Desfire manufacturing data in hex.

- src/main/java/au/id/micolous/metrodroid/card/tmoney/TMoneyCard.java
It is useful to read expiry date among other things
> tmoney: Read DF

- src/main/java/au/id/micolous/metrodroid/card/classic/ClassicCard.java
- src/main/java/au/id/micolous/metrodroid/transit/serialonly/SunCardTransitData.kt
- src/main/res/values/strings.xml
It has only serial stored on it
> SunCard from Orlando

- src/main/java/au/id/micolous/metrodroid/card/classic/ClassicCard.java
- src/main/java/au/id/micolous/metrodroid/transit/TransitCurrency.java
- src/main/java/au/id/micolous/metrodroid/transit/edy/EdyTransitData.java
- src/main/java/au/id/micolous/metrodroid/transit/kiev/KievTransitData.java
- src/main/java/au/id/micolous/metrodroid/transit/serialonly/IstanbulKartTransitData.java
- src/main/java/au/id/micolous/metrodroid/transit/serialonly/StrelkaTransitData.java
- src/main/java/au/id/micolous/metrodroid/transit/tmoney/TMoneyTransitData.java
- src/main/java/au/id/micolous/metrodroid/transit/zolotayakorona/ZolotayaKoronaRefill.kt
- src/main/java/au/id/micolous/metrodroid/transit/zolotayakorona/ZolotayaKoronaTransitData.kt
- src/main/java/au/id/micolous/metrodroid/transit/zolotayakorona/ZolotayaKoronaTrip.kt
- src/main/java/au/id/micolous/metrodroid/util/Utils.java
- src/main/res/values/strings.xml
Zolotaya Korona is MFC-based system used across Russia. I could get my hands
on 2 cards from Iaroslavl and one from Krasnodar.
> Implement parser for Zolotaya Korona.

- src/main/java/au/id/micolous/metrodroid/transit/ricaricami/RicaricaMiTransitData.java
> ricaricami: Add birth date.

- src/main/java/au/id/micolous/metrodroid/card/felica/FelicaCard.java
Felica lite has following quirks:
* No system code list
* At least some variants respond to any system code
* Attempting to read above 0x20 results in disconnected tag
While on it, fix to keep already read data in case of disconnect
> felica: code to read Felica Lite

- src/main/java/au/id/micolous/metrodroid/card/calypso/CalypsoApplication.java
- src/main/java/au/id/micolous/metrodroid/card/cepas/CEPASApplication.java
- src/main/java/au/id/micolous/metrodroid/card/iso7816/ISO7816Application.java
- src/main/java/au/id/micolous/metrodroid/card/iso7816/ISO7816File.java
- src/main/java/au/id/micolous/metrodroid/card/iso7816/ISO7816Protocol.java
- src/main/java/au/id/micolous/metrodroid/card/iso7816/ISO7816Selector.java
- src/main/java/au/id/micolous/metrodroid/card/iso7816/ISO7816SelectorById.java
- src/main/java/au/id/micolous/metrodroid/card/iso7816/ISO7816SelectorByName.java
- src/main/java/au/id/micolous/metrodroid/card/iso7816/ISO7816SelectorElement.java
This is necessarry for reading Pisa Carta Mobile
> Dump SFI files

- src/main/java/au/id/micolous/metrodroid/card/classic/ClassicCard.java
- src/main/java/au/id/micolous/metrodroid/card/classic/ClassicSector.java
- src/main/java/au/id/micolous/metrodroid/transit/easycard/EasyCardTopUp.kt
- src/main/java/au/id/micolous/metrodroid/transit/easycard/EasyCardTransaction.kt
- src/main/java/au/id/micolous/metrodroid/transit/easycard/EasyCardTransitData.kt
- src/main/java/au/id/micolous/metrodroid/transit/ovc/OVChipTransitData.kt
- src/main/java/au/id/micolous/metrodroid/transit/rkf/RkfTransitData.kt
- src/main/java/au/id/micolous/metrodroid/transit/selecta/SelectaFranceTransitData.kt
- src/main/java/au/id/micolous/metrodroid/transit/serialonly/SunCardTransitData.kt
- src/main/java/au/id/micolous/metrodroid/transit/zolotayakorona/ZolotayaKoronaTransitData.kt
This makes the code terser and more readable
> Use kotlin operators for accessing sectors/pages

- src/main/java/au/id/micolous/metrodroid/transit/easycard/EasyCardTransitData.kt
- src/main/java/au/id/micolous/metrodroid/transit/rkf/RkfTransitData.kt
- src/main/java/au/id/micolous/metrodroid/transit/selecta/SelectaFranceTransitData.kt
- src/main/java/au/id/micolous/metrodroid/transit/serialonly/SunCardTransitData.kt
- src/main/java/au/id/micolous/metrodroid/transit/zolotayakorona/ZolotayaKoronaTransitData.kt
Use kotlin constructs rather than JVM ones
> kotlin: idiomatize the code a bit

- src/main/java/au/id/micolous/metrodroid/card/classic/ClassicCard.java
- src/main/java/au/id/micolous/metrodroid/transit/chc_metrocard/ChcMetrocardTransitData.java
- src/main/java/au/id/micolous/metrodroid/transit/clipper/ClipperUltralightSubscription.java
- src/main/java/au/id/micolous/metrodroid/transit/clipper/ClipperUltralightTransitData.java
- src/main/java/au/id/micolous/metrodroid/transit/nextfare/NextfareTransitData.java
- src/main/java/au/id/micolous/metrodroid/transit/nextfare/ultralight/NextfareUltralightTransaction.java
- src/main/java/au/id/micolous/metrodroid/transit/nextfare/ultralight/NextfareUnknownUltralightTransaction.java
- src/main/java/au/id/micolous/metrodroid/transit/nextfare/ultralight/NextfareUnknownUltralightTransitData.java
- src/main/java/au/id/micolous/metrodroid/transit/serialonly/AtHopStubTransitData.java
- src/main/java/au/id/micolous/metrodroid/transit/troika/TroikaUltralightTransitData.java
- src/main/java/au/id/micolous/metrodroid/transit/unknown/BlankUltralightTransitData.java
- src/main/java/au/id/micolous/metrodroid/transit/unknown/UnauthorizedDesfireTransitData.java
- src/main/java/au/id/micolous/metrodroid/transit/unknown/UnauthorizedUltralightTransitData.java
- src/main/java/au/id/micolous/metrodroid/transit/zolotayakorona/ZolotayaKoronaTransitData.kt
Some overrides are exactly equal to super method
> Remove redundant overrides

- src/main/java/au/id/micolous/metrodroid/fragment/CardBalanceFragment.java
- src/main/java/au/id/micolous/metrodroid/transit/Subscription.java
- src/main/res/layout/subscription_item.xml
- src/main/res/values/strings.xml
It acts as number of remaining trips on cards that have it
> Show remaining days in upper part of subscription

- src/main/java/au/id/micolous/metrodroid/util/Utils.java
> Utils: Remove useless casts to char.

- src/main/java/au/id/micolous/metrodroid/transit/en1545/En1545FixedInteger.java
- src/main/java/au/id/micolous/metrodroid/transit/en1545/En1545Parsed.java
> en1545: Add support for local datetime

- src/main/java/au/id/micolous/metrodroid/card/XmlGenericCardFormat.java
- src/main/java/au/id/micolous/metrodroid/util/ExportHelper.java
String is final, so "? extends" has no effect
> Replace ? extends String with String

- src/main/java/au/id/micolous/metrodroid/card/XmlGenericCardFormat.java
- src/main/java/au/id/micolous/metrodroid/fragment/CardsFragment.java
- src/main/java/au/id/micolous/metrodroid/util/ExportHelper.java
- src/main/res/menu/cards_menu.xml
- src/main/res/values/strings.xml
This often happens after importing 2 different sets with common scans
> Code to deduplicate card scans

- src/main/java/au/id/micolous/metrodroid/card/classic/ClassicCard.kt
- src/main/java/au/id/micolous/metrodroid/transit/TransitCurrency.java
- src/main/java/au/id/micolous/metrodroid/transit/waikato/WaikatoRecord.kt
- src/main/java/au/id/micolous/metrodroid/transit/waikato/WaikatoTransitData.kt
- src/main/java/au/id/micolous/metrodroid/xml/ImmutableByteArray.kt
- src/main/res/values/strings.xml
Wiki notes: https://github.com/micolous/metrodroid/wiki/BUSIT
> Add support for Waikato/Hamilton BUSIT

- src/commonMain/kotlin/au/id/micolous/metrodroid/card/ultralight/UltralightTransitRegistry.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/serialonly/MRTUltralightTransitData.kt
Apparently no other useful data can be extracted from it without unlocking.
> Detect MRT (Singapore) single-trip tickets and show serial

- src/androidTest/java/au/id/micolous/metrodroid/test/ImportKeysTest.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/ClassicAuthenticator.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/key/ClassicCardKeys.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/key/ClassicKeys.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/key/ClassicKeysImpl.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/key/ClassicSectorKey.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/key/ClassicStaticKeys.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/util/ImmutableByteArray.kt
- src/main/java/au/id/micolous/metrodroid/fragment/KeysFragment.java
"Transformed" keys are essentially functions that need to be passed through some function ("transformation") before being usable on the card.
> Support for transformed keys

- extra/tng2json.py
- src/commonMain/kotlin/au/id/micolous/metrodroid/key/ClassicKeysImpl.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/key/ClassicSectorKey.kt
This does not include any actual keys, only a script to transform
them into a suitable format
Algorithm is contributed by @sumanblack666 and reimplemented by me
> Implement Touch 'n go key transformation

- src/jvmCommonMain/kotlin/au/id/micolous/metrodroid/serializers/XmlOrJsonFormat.kt
- src/main/java/au/id/micolous/metrodroid/fragment/CardsFragment.java
- src/main/res/menu/cards_menu.xml
- src/main/res/values/strings.xml
This avoids having to go through computer just to import a dump
> Support importing from MFC dump right in the application

- src/commonMain/kotlin/au/id/micolous/metrodroid/time/Timestamp.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/komuterlink/KomuterLinkTransitData.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/touchngo/TouchnGoTransitData.kt
It's actually the same time but technically correct timezone is Kuala Lumpur.
> Fix Malaysia time zone

- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/en1545/En1545Subscription.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/rkf/RkfLookup.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/rkf/RkfPurse.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/rkf/RkfTicket.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/rkf/RkfTransitData.kt
Huge thanks to the person who provided me with the dumps
> rkf: Support subscriptions

- src/commonMain/kotlin/au/id/micolous/metrodroid/serializers/classic/MctCardImporter.kt
Instead of filling them with zeros
> MctCardImporter: import unauthorized blocks as such

- src/commonMain/kotlin/au/id/micolous/metrodroid/card/CardType.kt
- src/main/java/au/id/micolous/metrodroid/fragment/CardsFragment.kt
Otherwise NfcV gets wrongly mapped to unknown
> CardType: fix reverse lookups

- src/commonMain/kotlin/au/id/micolous/metrodroid/card/UnauthorizedException.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/DesfireApplication.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/DesfireCardReader.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/DesfireCardTransitFactory.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/DesfireCardTransitRegistry.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/DesfireProtocol.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/files/DesfireFile.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/files/RawDesfireFile.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/files/StandardDesfireFile.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/files/ValueDesfireFile.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/magnacarta/MagnaCartaTransitData.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/unknown/UnauthorizedDesfireTransitData.kt
- src/main/res/values/strings.xml
I don't have such a card myself but I could format a Desfire card in a similar
way and now both MensaGuthaben and Metrodroid give the same result on it
> Support MagnaCarta based on info from MensaGuthaben

- src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/DesfireCardTransitRegistry.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/settings/ValueDesfireFileSettings.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/intercard/IntercardTransitData.kt
- src/main/res/values/strings.xml
This is a stored value card used in German and Swiss school canteens
> New card: Intercard

- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/serialonly/SunCardTransitData.kt
> SunCard: Mark as not requiring the keys

- src/androidTest/java/au/id/micolous/metrodroid/test/DateTest.kt
> Add test for Date code

- src/androidTest/java/au/id/micolous/metrodroid/test/ClassicReaderTest.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/ClassicReader.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/ClassicSector.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/ClassicSectorValid.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/bonobus/BonobusTransitData.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/charlie/CharlieCardTransitData.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/kiev/KievTransitData.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/metromoney/MetroMoneyTransitData.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/podorozhnik/PodorozhnikTransitData.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/rkf/RkfTransitData.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/smartrider/SmartRiderTransitData.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/troika/TroikaHybridTransitData.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/util/HashUtils.kt
While on it remove getKey() on sector in favor of getKeyA and getKeyB
> Show both keys in raw MFC view when available.

- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/ricaricami/RicaricaMiLookup.kt
> Add monthly and yearly subscription codes for ATM (Milan, Italy)

- README.md
> Rejsekort is danish, language fixes

- src/main/java/au/id/micolous/metrodroid/card/CardReader.kt
- src/main/java/au/id/micolous/metrodroid/fragment/CardsFragment.kt
- src/main/java/au/id/micolous/metrodroid/fragment/KeysFragment.kt
- src/main/java/au/id/micolous/metrodroid/key/InsertKeyTask.kt
- src/main/java/au/id/micolous/metrodroid/serializers/XmlPullParserIterator.kt
- src/main/java/au/id/micolous/metrodroid/util/BetterAsyncTask.kt
- src/main/java/au/id/micolous/metrodroid/util/ExportHelper.kt
They're not necessarry anymore and sometimes wrong, so just kill them
> Remove @Throws annotation

- extra/mfcdump_convert.py
It should be just 'type', not 'keytype'
> Fix mfcdump_convert

- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/TransitCurrency.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/komuterlink/KomuterLinkTransitData.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/touchngo/TouchnGoTransitData.kt
- src/main/res/values/strings.xml
Transaction counter, travel pass and few cleanups
>  touchngo: add transaction counter and travel pass

- src/commonMain/kotlin/au/id/micolous/metrodroid/card/felica/FelicaCard.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/card/felica/FelicaReader.kt
PMM is more difficult to retrieve on iOS and we don't really care about it,
so make it optional
> felica: make pmm optional

- src/main/java/au/id/micolous/metrodroid/activity/ReadingTagTask.kt
- src/main/java/au/id/micolous/metrodroid/util/Utils.kt
Currently we ignore it on some code paths but not others. Be more
consistent and ignore it on more paths. Write extension safeShow to
simplify this
> Always ignore BadTokenException

- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/Trip.kt
- src/main/java/au/id/micolous/metrodroid/fragment/CardTripsFragment.kt
description clashes with swift's equivalent of toString()
> Trip.Mode: Rename description to contentDescription

- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/en1545/Calypso1545TransitData.kt
- src/jvmCommonMain/kotlin/au/id/micolous/metrodroid/util/StationTableReader.kt
- src/main/java/au/id/micolous/metrodroid/activity/AdvancedCardInfoActivity.kt
- src/main/java/au/id/micolous/metrodroid/activity/ReadingTagActivity.kt
- src/main/java/au/id/micolous/metrodroid/fragment/CardsFragment.kt
- src/main/java/au/id/micolous/metrodroid/util/ExportHelper.kt
Travis has comehow pulled a newer kotlin compiler and hence it needs few
fixes and workarounds.
> Compile fixes and workarounds for new compiler.

- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/metromoney/MetroMoneyTransitData.kt
I don't have suitably annotated dumps to understand what they mean but
I feel like putting them in raw fields is ok until we figure out what they are
> metromoney: Put 4 unknown dates into raw fields

- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/ovc/OVChipTransitData.kt
- src/main/res/values-fr/strings.xml
- src/main/res/values-it/strings.xml
- src/main/res/values-ja/strings.xml
- src/main/res/values-nb-rNO/strings.xml
- src/main/res/values-nl/strings.xml
- src/main/res/values-ru/strings.xml
- src/main/res/values/strings.xml
For several strings either rephrase them or add an explanatory comment
> String improvements

- src/main/res/layout/list_header.xml
- src/main/res/values/attrs.xml
- src/main/res/values/themes.xml
Farebot theme broke in androidx migration. Fix it.
> Fix Farebot theme

- native/metrodroid/metrodroid.xcodeproj/project.pbxproj
packForXcode was changed not to create gradlew but
the ath to gradlew was not changed
> project: change path to gradlew

- data/clipper/mapping_bart.csv
Based on https://github.com/codebutler/farebot/pull/182
> clipper: Mark Warm Springs as confirmed

- native/metrodroid/metrodroid.xcodeproj/project.pbxproj
> project.pbxproj: Fix duplicate file registration

- docs/ios.md
- native/metrodroid/metrodroid/CardPersister.swift
- native/metrodroid/metrodroid/HistoryViewController.swift
- src/commonMain/kotlin/au/id/micolous/metrodroid/card/Card.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/multi/Misc.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/serializers/CardSerializer.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/serializers/XmlCardFormat.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/Subscription.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/TransitData.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/util/Base64.kt
- src/iOSMain/kotlin/au/id/micolous/metrodroid/card/classic/PlusCardReaderIOS.kt
- src/iOSMain/kotlin/au/id/micolous/metrodroid/card/desfire/DesfireCardReaderIOS.kt
- src/iOSMain/kotlin/au/id/micolous/metrodroid/card/felica/FelicaCardReaderIOS.kt
- src/iOSMain/kotlin/au/id/micolous/metrodroid/card/iso7816/ISO7816CardReaderIOS.kt
- src/iOSMain/kotlin/au/id/micolous/metrodroid/card/ultralight/UltralightCardReaderIOS.kt
- src/iOSMain/kotlin/au/id/micolous/metrodroid/transit/TransitDataStored.kt
- src/jvmCommonMain/kotlin/au/id/micolous/metrodroid/serializers/NodeWrapperImpl.kt
- src/main/java/au/id/micolous/metrodroid/multi/Misc.kt
This is on top of my "docpick" branch
> Support importing XML on iOS

- src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/ClassicCardFactoryRegistry.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/cifial/CifialTransitData.kt
- src/main/res/values/strings.xml
These are used as keycards in hotels across the world. Parse them and show
room number, check-in and check-out.
> Support Cifial cards

- native/metrodroid/metrodroid/CardPersister.swift
- native/metrodroid/metrodroid/HistoryViewController.swift
- src/commonMain/kotlin/au/id/micolous/metrodroid/serializers/CardSerializer.kt
This adds large file warning and farebot import on iOS
> ios: Support farebot json import

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- Gradle: 5.1.1 -> 5.4.1
- Android Gradle Plugin: 3.4.1 -> 3.5.0
> Updates to dependencies (Gradle 5.4.1)

- src/commonMain/kotlin/au/id/micolous/metrodroid/key/ClassicKeysImpl.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/key/ClassicSectorKey.kt
I forgot to export it, fixing this.
> Export bundle when exporting the keys

- src/main/java/au/id/micolous/metrodroid/fragment/TreeListFragment.kt
Rather than doing it manually just use library function
> TreeListFragment: Use TextViewCompat.setTextAppearance

- src/main/java/au/id/micolous/metrodroid/fragment/CardTripsFragment.kt
localizeFormatted already adds the span if LocaleSpan is enabled.
Simplify the code
> CardTripsFragment: Use localizeFormatted rather than adding LocaleSpan.

- .gitmodules
- build.gradle
- jvmcli/README.md
- jvmcli/build.gradle
- jvmcli/windows.md
- settings.gradle
- src/commonMain/kotlin/au/id/micolous/metrodroid/card/iso7816/ISO7816TLV.kt
- src/commonTest/kotlin/au/id/micolous/metrodroid/test/BERTLVTest.kt
- src/commonTest/kotlin/au/id/micolous/metrodroid/test/SimpleTLVTest.kt
- src/jvmCliMain/kotlin/au/id/micolous/metrodroid/Cli.kt
- src/jvmCliMain/kotlin/au/id/micolous/metrodroid/card/Atr.kt
- src/jvmCliMain/kotlin/au/id/micolous/metrodroid/card/JavaCardTransceiver.kt
- src/jvmCliMain/kotlin/au/id/micolous/metrodroid/card/PCSCAtr.kt
- src/jvmCliMain/kotlin/au/id/micolous/metrodroid/cli/SmartCard.kt
- src/jvmCliTest/kotlin/au/id/micolous/metrodroid/test/AtrTest.kt
- src/jvmCommonMain/kotlin/au/id/micolous/metrodroid/util/ExportHelper.kt
- src/main/java/au/id/micolous/metrodroid/activity/AdvancedCardInfoActivity.kt
- src/main/java/au/id/micolous/metrodroid/util/ExportHelper.kt
(Uses #599, https://github.com/OpenJavaCard/openjavacard-smartcardio/pull/3, #683)
This adds basic support for working with PC/SC-compatible smartcard readers in `jvmCli`.  I've added documentation with known issues and limitations to this.
I've tested reading cards using macOS and Windows 10.
> jvmCli: Add support for PC/SC compatible readers

- README.md
> Updated supported cards list for 3.0.0

- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/orca/OrcaTransaction.kt
> orca: Fix Seattle Monorail, show raw data flelds

- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/zolotayakorona/ZolotayaKoronaTransitData.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/zolotayakorona/ZolotayaKoronaTrip.kt
- src/main/res/values/strings.xml
In the same time show more raw fields
> zolotayakorona: Show discount type

- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/smartrider/SmartRiderTagRecord.kt
Canberra Light Rail has route set to `RAIL`, like SmartRider train journeys.
> myway: add Canberra Light Rail

- extra/mfcdump_convert.py
> Added Mifare Plus 2k support to convert script

- src/main/res/values/strings.xml
Based on retranslation of japanese strings and sross-referencing with search results
> Attempt to clarify felica transactions

- build.gradle
- src/main/res/layout/activity_about.xml
- src/main/res/layout/activity_main.xml
- src/main/res/values/attrs.xml
- src/main/res/values/themes.xml
Color can be adjusted. I've chosen green to match the logo but we can choose
another color
> Switch to material design

- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/clipper/ClipperUltralightTransitData.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/edy/EdyTrip.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/kiev/KievTrip.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/kmt/KMTTrip.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/nextfare/NextfareTrip.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/touchngo/TouchnGoTransitData.kt
- src/main/res/values/strings.xml
> Add unused fields to getRawFields

- src/commonTest/kotlin/au/id/micolous/metrodroid/test/DateTest.kt
Previously we had our own date implementation and were testing it by
comparing against system implementation
Now we use kotlin.datetime which bridges to system implementation and/or
310 backport, so comparing it against a naive own implementation is
appropriate.
It allows us to make DateTest into a common test
> Rewrite and uplift DateTest

- src/commonMain/kotlin/au/id/micolous/metrodroid/serializers/CardSerializer.kt
- src/jvmCliMain/kotlin/au/id/micolous/metrodroid/Cli.kt
- src/main/java/au/id/micolous/metrodroid/activity/AdvancedCardInfoActivity.kt
It ended up being compact instead
> Make exported and stored json's pretty as intended

- src/main/java/au/id/micolous/metrodroid/activity/CardInfoActivity.kt
Based on top of ViewPager2 patchin order to avoid conflicts
> CardInfoActivity: Convert to coroutines

- src/commonMain/kotlin/au/id/micolous/metrodroid/card/emv/EmvCard.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/card/iso7816/ISO7816Data.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/card/iso7816/ISO7816TLV.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/card/iso7816/TagDesc.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/emv/EmvData.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/emv/EmvLogEntry.kt
- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/emv/EmvTransitData.kt
- src/jvmCliMain/kotlin/au/id/micolous/metrodroid/Cli.kt
- src/main/res/values/strings.xml
Atto.uz cards are largely EMV cards. Improve handling of some of the fields it uses
> Several EMV improvement based on atto.uz cards

- src/commonMain/kotlin/au/id/micolous/metrodroid/util/IteratorUtils.kt
- src/jvmCommonMain/kotlin/au/id/micolous/metrodroid/serializers/XmlOrJsonFormat.kt
- src/jvmCommonMain/kotlin/au/id/micolous/metrodroid/serializers/XmlPullParserIterator.kt
- src/jvmCommonMain/kotlin/au/id/micolous/metrodroid/util/UtilsJvm.kt
This removes the need of loading entire list of card in xml file if
it's inside of zip.
This branch is on top of xmlstr branch and PR
> Change zip parsing through using of iterators

- src/commonMain/kotlin/au/id/micolous/metrodroid/transit/ovc/OVChipTransitData.kt
On my card, a PURCHASE just happens to have the same transaction ID as a CHECKIN, which hides the tagOn from the TransactionTrip correlation. This change will ignore any of these purchase transactions when deduplicating the tagOn/tagOff events, to prevent this rare event from happening.
> OV-Chipkaart: Ignore reloads when deduping taggings
