metrodroid/metrodroid

src/main/AndroidManifest.xml, src/main/java/au/id/micolous/metrodroid/activity/AddKeyActivity.java, src/main/java/au/id/micolous/metrodroid/activity/CardsActivity.java, src/main/java/au/id/micolous/metrodroid/activity/KeysActivity.java
Metrodroid reads only files from its own directory and through
StorageAccessFramework. Neither of them needs permission be it in
manifest or runtime.
=> Remove storage permission on API >= 19

src/main/java/au/id/micolous/metrodroid/transit/TransitCurrency.java
All users of JPY use TransitCurrency.JPY, so special handling
of "JPY" symbol is no longer required.
Remove unused imports.
=> Cleanup TransitCurrency.

src/main/java/au/id/micolous/metrodroid/fragment/CardTripsFragment.java, src/main/java/au/id/micolous/metrodroid/transit/Trip.java, src/main/res/values/strings.xml
Current solution is to pretend that end time/station is start time/station
if no real start data is available. It's confusing as there is no
distinguishing between start and end visually and hence it can be assumed
it's a start of a journey rather than the end. It's tolerable for occasional
hiccup but Shenzhen Tong has only ending stations AFAICT.
=> Support showing trips without starting time or location

src/main/AndroidManifest.xml, src/main/java/au/id/micolous/metrodroid/fragment/CardsFragment.java, src/main/res/xml/provider_paths.xml
Export all pushes the file size up by a lot. So old code doesn\t work with this
file size. This fixes several issues:
* Writing/reading files/sharing has to be done in async tasks with at most
a weak reference to fragment (strictmode and everything)
* file is too large to fit in a parcel atached to intent. So it needs to be
saved and then passed as an URI.
* Missing close() call resulted in 0-size files when saving to drive
Paths for pre-KitKat were left alone as it's less of an issue.
=> Fix import and export functionality.

src/main/java/au/id/micolous/metrodroid/MetrodroidApplication.java, src/main/java/au/id/micolous/metrodroid/util/StationTableReader.java, src/main/res/values/strings.xml, src/main/res/xml/prefs.xml
This is useful both for devs to check that both names are determined
correctly and for the end users who may know some of foreign language
and may be willing to compare visually with writings.
=> Allow showing both local and English name at the same time

src/androidTest/java/au/id/micolous/metrodroid/test/StationTableReaderTest.java, src/main/java/au/id/micolous/metrodroid/MetrodroidApplication.java, src/main/java/au/id/micolous/metrodroid/transit/lax_tap/LaxTapData.java, src/main/java/au/id/micolous/metrodroid/transit/lax_tap/LaxTapTrip.java, src/main/java/au/id/micolous/metrodroid/transit/ovc/OVChipTrip.java, src/main/java/au/id/micolous/metrodroid/transit/seq_go/SeqGoTrip.java, src/main/java/au/id/micolous/metrodroid/transit/suica/SuicaDBUtil.java, src/main/java/au/id/micolous/metrodroid/util/StationTableReader.java
This allows avoid to change MetrodroidApplication every time a new DB is needed.
=> Move mdst names out of MetrodroidApplication.

src/main/java/au/id/micolous/metrodroid/card/desfire/DesfireManufacturingData.java
It's necessarry to unlock Leap cards.
=> Desfire: save raw manufacturing data.

src/main/java/au/id/micolous/metrodroid/MetrodroidApplication.java, src/main/java/au/id/micolous/metrodroid/transit/Station.java, src/main/java/au/id/micolous/metrodroid/transit/clipper/ClipperData.java, src/main/java/au/id/micolous/metrodroid/transit/newshenzhen/NewShenzhenTrip.java, src/main/java/au/id/micolous/metrodroid/util/StationTableReader.java, src/main/res/values/strings.xml, src/main/res/xml/prefs.xml
This is useful when debugging or collecting database
While on it add a generic way to add "attributes" to stations, like e.g.
gate number. This will be reused in, at least, Podorozhnik.
=> Add option to always show raw station IDs

src/main/java/au/id/micolous/metrodroid/fragment/CardTripsFragment.java, src/main/java/au/id/micolous/metrodroid/transit/Trip.java, src/main/java/au/id/micolous/metrodroid/transit/clipper/ClipperRefill.java, src/main/java/au/id/micolous/metrodroid/transit/clipper/ClipperTrip.java, src/main/java/au/id/micolous/metrodroid/transit/compass/CompassUltralightTrip.java, src/main/java/au/id/micolous/metrodroid/transit/edy/EdyTrip.java, src/main/java/au/id/micolous/metrodroid/transit/erg/ErgTrip.java, src/main/java/au/id/micolous/metrodroid/transit/ezlink/EZLinkTrip.java, src/main/java/au/id/micolous/metrodroid/transit/hsl/HSLRefill.java, src/main/java/au/id/micolous/metrodroid/transit/newshenzhen/NewShenzhenTrip.java, src/main/java/au/id/micolous/metrodroid/transit/orca/OrcaTrip.java, src/main/java/au/id/micolous/metrodroid/transit/ovc/OVChipTrip.java, src/main/java/au/id/micolous/metrodroid/transit/ravkav/RavKavTrip.java, src/main/java/au/id/micolous/metrodroid/transit/smartrider/SmartRiderTrip.java, src/main/java/au/id/micolous/metrodroid/transit/tmoney/TMoneyTrip.java, src/main/java/au/id/micolous/metrodroid/transit/troika/TroikaTrip.java
Only very few cards store day but not time. So change logic to
automatically detect null datetime as hasTime = null and leave override only
when really necessarry.
=> Remove the need to always override hasTime

src/main/java/au/id/micolous/metrodroid/card/classic/ClassicBlock.java, src/main/java/au/id/micolous/metrodroid/card/classic/ClassicSector.java, src/main/java/au/id/micolous/metrodroid/fragment/ClassicCardRawDataFragment.java, src/main/res/values/strings.xml
On some cards there are a lot of empty sectors which makes it
cumbersome to check that there is no new data in a new dump. So mark
empty sectors as such.
=> Mark empty sector on Mifare Classic as such

src/main/java/au/id/micolous/metrodroid/transit/nextfare/record/NextfareTransactionRecord.java
They're present on Minneapolis cards and don't seem to provide any data
=> nextfare: Skip record of type 0x89

src/main/java/au/id/micolous/metrodroid/fragment/KeysFragment.java
We don't support XML keys. Add x-extesion-bin to accepted types
=> Fix MIME-types for keys.

src/main/java/au/id/micolous/metrodroid/MetrodroidApplication.java
Farebot theme creates unescapable crash under Kitkat or earlier. Fix it
=> Fix crash on pre-lollipop android

src/main/java/au/id/micolous/metrodroid/activity/AdvancedCardInfoActivity.java
Without it exporting a single card to google drive results in zero-sized file.
=> Add missing os.close()

data/orca/agencies.csv
Rode two buses and the fast ferry (using a [PFTP](https://www.flickr.com/photos/viriyincy/3561731244/)); all showed up as agency 5.
=> Add Kitsap Transit to ORCA

data/orca/stations.csv
This data came from a dump from @SoundTransit that provided the following:
|#|Location|
|-|-|
|4211091569|Angle Lake|
|150994945|Everett|
|150994946|Edmonds|
|150994947|King Street|
|150994948|Tukwila|
|150994949|Kent|
|150994950|Auburn|
|150994951|Sumner|
|150994952|Puyallup|
|150994953|Tacoma Dome|
|151002625|Mukilteo|
|151002626|Lakewood|
|151009253|South Tacoma|
Looking at King Street, if we convert `150994947` to hex, we get `9000003`.  I have no idea what the 9 means.  The existing data here shows `458755` for King Street, and converting that in hex is `70003`.  That one makes a little more sense, as `7` is the ID for Sound Transit, which is the agency responsible for the fare reader/writers at this station.
This methodology falls apart for the last three stations so I've omitted …
=> Update ORCA stations

src/main/java/au/id/micolous/metrodroid/card/classic/ClassicCard.java
It makes no sense to add well-known keys to user list, so pretend that
they are always in the list.
This speeds up scanning hugely as current code waits to bruteforce all
keys.
=> Try well-known keys at the same time as loaded static keys

src/main/java/au/id/micolous/metrodroid/key/ClassicStaticKeys.java
Many keys are repeated in static keysets, no need to try them a lot of times.
=> When trying alternate static keys dedup them.

src/main/java/au/id/micolous/metrodroid/MetrodroidApplication.java
My Oppo Find 7 device (running LineageOS) is not working with the unpatched version as Metrodroid says that Mifare Classic support is not there.
After whitelisting, my device can read cards without problems.
=> Add Oppo Find7 to whitelist - device is working here after whitelisting

src/main/java/au/id/micolous/metrodroid/transit/ovc/OVChipCredit.java
OVC inverts the sign bit, add a XOR to compensate
Thanks to @sfeigl
=> Fix OVC credit retrieval.

src/main/java/au/id/micolous/metrodroid/fragment/CardBalanceFragment.java
If a card has many subscriptions, it can happen that view are reused (convertView is non-null).
If a BalanceView is reused as a SubscriptionView (or vice versa), this leads to a crash of the
application as findById returns null for sub-views.
When a card does not have many subscriptions, the bug is not triggered here, as the views are
not reused.
I used getTag()/setTag() to mark the views and check whether they are the correct type. An easier
fix would be to always discard "convertView". You could also check for a unique view id with
findById(), but IMHO this is more error-prone.
Error I get when view is reused incorrectly:
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setVisibility(int)' on a null object reference
at …
=> Fix potential crash due to reusing view of incorrect type.

src/androidTest/java/au/id/micolous/metrodroid/test/TransitCurrencyTest.java, src/main/java/au/id/micolous/metrodroid/transit/TransitCurrency.java, src/main/java/au/id/micolous/metrodroid/transit/rkf/RkfLookup.kt, src/main/java/au/id/micolous/metrodroid/util/Utils.java
Comparison between doubles is unpredictable. Use integer as much as possible.
=> TransitCurrency: switch to integer math

extra/farebotxml_to_files.py
Without zip64 we're limited to just a few thousand files which
can be easily hit if you have a lot of ultralight scans
=> Allow zip64 in farebotxml_to_files

src/main/java/au/id/micolous/metrodroid/transit/en1545/Calypso1545TransitData.java
In some cases an unrelated file might get ID of counters_9 and thus
prevent from looking up counters_[1-4]
=> calypso: Try LFI-selected files before SFI

extra/mdst/compile_stops_from_gtfs.py
We rarely use both, so no need to always have second column
=> Allow one of stop_id or stop_code to be missing

src/main/java/au/id/micolous/metrodroid/transit/lax_tap/LaxTapData.java, src/main/java/au/id/micolous/metrodroid/transit/seq_go/SeqGoData.java
It needlessly creates a new child class rather than just an instance of base
class
=> Remove double brace initialization

src/main/java/au/id/micolous/metrodroid/MetrodroidApplication.java
This prevents possible inadvertent reference to parent context
=> Make Visitor a static class

src/main/java/au/id/micolous/metrodroid/transit/en1545/Calypso1545TransitData.java
They're already in parent class
=> Kill unused en1545 strings.

src/main/java/au/id/micolous/metrodroid/card/iso7816/ISO7816Application.java
It's not actually useful and breaks encapsulation.
=> iso7816: remve getFiles

src/main/java/au/id/micolous/metrodroid/card/calypso/CalypsoApplication.java, src/main/java/au/id/micolous/metrodroid/card/china/ChinaCard.java, src/main/java/au/id/micolous/metrodroid/card/iso7816/ISO7816ApplicationFactory.java, src/main/java/au/id/micolous/metrodroid/card/iso7816/ISO7816Card.java, src/main/java/au/id/micolous/metrodroid/card/tmoney/TMoneyCard.java
This is needed when entry-point app references another app by its ID
that is not known in advance
=> Allow iso7816 dumptag to return several applications.

src/main/java/au/id/micolous/metrodroid/card/iso7816/ISO7816Application.java, src/main/java/au/id/micolous/metrodroid/card/iso7816/ISO7816Card.java, src/main/java/au/id/micolous/metrodroid/card/iso7816/ISO7816File.java, src/main/java/au/id/micolous/metrodroid/card/iso7816/ISO7816TLV.kt, src/main/java/au/id/micolous/metrodroid/transit/china/NewShenzhenTransitData.java, src/main/java/au/id/micolous/metrodroid/transit/tmoney/TMoneyTransitData.java
* Extract to separate class
* Convert to kotlin
* Use kotlin syntax to make it nicer and more reusable
* Add parsed FCI to raw tab
* Change ID to hex string. Current ID was done under false assumption that
9f05 and 95 are the same. It's not the case, so use hex string, same as
used in the documentation.
=> TLV improvements

src/main/java/au/id/micolous/metrodroid/card/Card.java, src/main/java/au/id/micolous/metrodroid/card/classic/ClassicCard.java, src/main/java/au/id/micolous/metrodroid/card/felica/FelicaCard.java, src/main/java/au/id/micolous/metrodroid/card/iso7816/ISO7816Card.java
It's filled only through deserialization and never directly
=> Card: Remove label from constructors

src/main/java/au/id/micolous/metrodroid/transit/en1545/Calypso1545TransitData.java, src/main/java/au/id/micolous/metrodroid/transit/opus/OpusTransitData.java
This getSerial function is used only by Opus, so just move it there.
=> Move getSerial from Calypso to Opus

src/commonMain/kotlin/au/id/micolous/metrodroid/transit/ezlink/EZLinkTrip.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/ezlinkcompat/EZLinkCompatTrip.kt
This created a lot of code duplication and it was overseen that strings like
"ABC DE" as POS seller would crash the parser
=> Merge different paths of parsing EZ-link userData

src/commonMain/kotlin/au/id/micolous/metrodroid/card/UnauthorizedException.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/DesfireCard.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/DesfireCardReader.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/DesfireProtocol.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/unknown/UnauthorizedDesfireTransitData.kt
RabbitCard has a locked PICC, so we can't read the list of applications,
yet if we select right app, the selection will succeed.
Apps are similar to Thailand BEM but BEM has few more apps, use them for
distinguishing.
=> Detect Rabbit card and show it as such.

src/commonMain/kotlin/au/id/micolous/metrodroid/transit/Subscription.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/Transaction.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/TransactionTrip.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/TransitData.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/Trip.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/en1545/Calypso1545TransitData.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/en1545/En1545Subscription.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/en1545/En1545Transaction.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/en1545/En1545TransitData.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/util/Preferences.kt, src/main/java/au/id/micolous/metrodroid/activity/CardInfoActivity.java, src/main/java/au/id/micolous/metrodroid/fragment/CardBalanceFragment.java, src/main/java/au/id/micolous/metrodroid/fragment/CardInfoFragment.java, src/main/java/au/id/micolous/metrodroid/fragment/CardTripsFragment.java, src/main/java/au/id/micolous/metrodroid/util/Preferences.kt, src/main/res/values/strings.xml, src/main/res/xml/prefs.xml
This preference has 3 levels: none, only unknown or all.
This is very useful when riding on transit and reverse engineering the
card, especially after having some idea of the layout but not all
=> Add preference to show raw fields.

src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/ClassicAuthenticator.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/ClassicBlock.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/ClassicReader.kt, src/main/java/au/id/micolous/metrodroid/card/classic/ClassicCardTechAndroid.kt
1. Some cards have broken auth responses and successfuly authenticate with
a readable B key. Detect this case and continue searching for key A
2. In Android Q, readBlock on unauthorized block returns an exception instead of
byteArrayOf(0x04). So assume any IOException other than TagLost is an
authentication error.
3. Make log statement a bit more verbose
=> MifareClassic reader authentication fixes

src/commonMain/kotlin/au/id/micolous/metrodroid/transit/charlie/CharlieCardTransitData.kt
The magic is shared with PortAuthority, so check the keys instead to
exclude false positives.
=> charlie: Change identification to check keys

src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/DesfireCardReader.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/DesfireCardTransitFactory.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/unknown/UnauthorizedDesfireTransitData.kt
This moves app ID list to transit data and so allows reading in future other
cards with locked PICC without putting IDs in card/desfire directory
=> Cleanup locked app list handling

src/commonMain/kotlin/au/id/micolous/metrodroid/card/UnauthorizedException.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/DesfireApplication.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/DesfireCardReader.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/DesfireCardTransitFactory.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/DesfireProtocol.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/files/DesfireFile.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/files/RawDesfireFile.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/files/StandardDesfireFile.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/files/ValueDesfireFile.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/unknown/UnauthorizedDesfireTransitData.kt
MagnaCarta locks down the directory list. It doesn't prevent us from iterating
through files as there are only 256 possible file IDs and only 32 that are
ever used in any parser. However we can't read file settings in this case
so instead we have to try all 3 possible read command and then save which one
worked for recreating the parsed files
=> Support desfire cards with locked directory list 

src/commonMain/kotlin/au/id/micolous/metrodroid/transit/Transaction.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/TransactionTrip.kt
Most systems do not record seconds. It's common to topup and go through
the gate in the same minute. In this case topup may end up being sorted after
tap-in and hence prevent tap-in and tap-out merging.
=> TransactionTrip: Skip topup transactions while merging.

extra/mfcdump_convert.py
This is required to make the code compatible with both python2 and
python3
=> mfcdump_convert: Add missing codecs wrapping

src/androidTest/java/au/id/micolous/metrodroid/test/TLVDroidTest.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/emv/EmvCard.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/iso7816/ISO7816TLV.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/emv/EmvData.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/emv/EmvLogEntry.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/util/ImmutableByteArray.kt, src/commonTest/kotlin/au/id/micolous/metrodroid/test/ImmutableByteArrayTest.kt, src/commonTest/kotlin/au/id/micolous/metrodroid/test/TLVTest.kt
* decodeTLVLen now supports indefinite TLV form
* Skip NULL bytes between fields per EMV spec (fixes reading Monzo
Mastercard -- but no transaction history available)
* Converts decodeTLVLen to use Triple instead of IntArray
* decodeTLVLen now doesn't try to decode larger than 61 bit integers
* decodeTLVLen aborts when getting a field larger than 0xFFFF bytes, which
should be enough for anyone
* Moves some EMV constants into EmvData
* Add test for TLV decoder
=> EMV fixups

data/clipper/stations.csv
- Add two new San Francisco Bay Ferry stations, SF Pier 41 & Oakland
- Remove a extra comma in the CSV header
=> Improve Clipper stations data

src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/DesfireCardTransitRegistry.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/serialonly/NolTransitData.kt, src/main/res/values/strings.xml
It's the same implementer and AFAICT the same format as At HOP, so
only serial number is readable
=> New card: Nol Card from Dubai (serial-only)

build.gradle
In debug build we're not too far from 64K method limit, so add this to
keep an eye on the problem.
=> Add dexcount to build

build.gradle
This silence the warnings about usage of unsigned types
=> Add unsigned compile options

src/main/java/au/id/micolous/metrodroid/fragment/CardsFragment.kt, src/main/res/menu/cards_menu.xml
It fixes the underlying context bug.
Copy all is not useful anymore as the zip is not text
=> Bring back "Share all" option

src/commonMain/kotlin/au/id/micolous/metrodroid/transit/kazan/KazanTransitData.kt
I discovered cards where block 0.0 is locked in access conditions
that don't allow reading. Workaround by using 14a metadata
=> kazan: Read tagId from metadata rather than block 0

src/androidTest/java/au/id/micolous/metrodroid/test/ClassicCardTest.kt, src/androidTest/java/au/id/micolous/metrodroid/test/ClassicManufacturerDataTest.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/ClassicCard.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/multi/FormattedString.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/ui/ListItem.kt, src/commonTest/assets/mfc/mfc-incomplete0.json, src/commonTest/assets/mfc/mfc-incomplete1.json, src/commonTest/kotlin/au/id/micolous/metrodroid/test/Utils.kt
* fix a crash in manufacturingInfo if sector 0 block 0 was not read
* separate NXP and Fudan manufacturer entries into static items for easier testing
* FormattedString: add .equals method
* ListItem: add .equals and .hashCode methods
* test.Utils: add assert(Not)?ContainsListItem
* add regression tests for Classic manufacturerInfo
* add regression test for incomplete Classic manufacturerInfo
```
Caused by: java.lang.IndexOutOfBoundsException: 
at kotlin.collections.EmptyList.get (Collections.kt:34)
at kotlin.collections.EmptyList.get (Collections.kt:22)
at au.id.micolous.metrodroid.card.classic.ClassicCard.getManufacturingInfo (ClassicCard.kt:50)
at au.id.micolous.metrodroid.card.Card.getManufacturingInfo (Card.kt:109)
at au.id.micolous.metrodroid.activity.AdvancedCardInfoActivity.onCreat …
```
=> ClassicCard: fix edge cases with incomplete reads

src/commonMain/kotlin/au/id/micolous/metrodroid/transit/kmt/KMTTransitData.kt
Some how they updated the system time to 6 hours earlier. I just noticed this morning.
=> KMT_EPOCH Fix

src/commonMain/kotlin/au/id/micolous/metrodroid/transit/amiibo/AmiiboTransitData.kt
If the tag is read through NfcA codepath rather than ultralight codepath, then
model is not populated, so accept this case if number of pages matches
=> amiibo: Check number of pages as an alternative to model

src/main/java/au/id/micolous/metrodroid/multi/Localizer.kt, src/main/java/au/id/micolous/metrodroid/util/ExportHelper.kt, src/main/java/au/id/micolous/metrodroid/util/Utils.kt, src/main/res/values/strings.xml
In README.txt first string is always in English and the rest is in local
language.
Instead, create 2 readme's: one in English and one in local language.
=> Fix localization situation with README.txt

src/commonMain/kotlin/au/id/micolous/metrodroid/transit/Subscription.kt, src/main/res/values/strings.xml
Some languages e.g. Russian have different handling for plurals when
the numeral is present and when it's not. E.g. in Russian
For 1: "1 Zona" or simply "Zona"
For 21: "21 Zona" but "Zony" if number is not explicitly specified
As you can see in the presence of numeral both 1 and 21 use the same form but
not in its absence.
Unfortunately Android uses form "one" for both 1 and 21. So it supports only
strings with explicit numeral.
So add the explicit numeral or provide an alternative
=> Avoid unsupported plurals without explicit numeral

src/main/java/au/id/micolous/metrodroid/fragment/CardBalanceFragment.kt
Company and pax have the same height dictated by company
hence we need to show company if we want to show pax
even if company is empty
=> sub: fix showing pax when no company name is present

src/commonMain/kotlin/au/id/micolous/metrodroid/transit/Subscription.kt, src/main/java/au/id/micolous/metrodroid/fragment/CardBalanceFragment.kt
This is to avoid conflict with swift's description (analog of toString()).
=> SubscriptionState: Replace description with descriptionRes

src/main/res/values/strings.xml
This is the only place where we use string-array. Rather than supporting
it in iOS code, just split it into separate string's.
Addensum: it looks like weblate also ignores string-array's which makes this more important and not limited to iOS
=> strings: split raw_levels into separate string's

src/commonMain/kotlin/au/id/micolous/metrodroid/transit/TransitName.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/util/StationTableReader.kt, src/jvmCommonMain/kotlin/au/id/micolous/metrodroid/util/StationTableReader.kt
* Move post-processing logic to common main
* Move proto/file reading integration to jvm-common
* Encapsulate name-related concepts into new class TransitName
* Make StationTableReader an interface for better separation
It's on top of valid2 branch
=> Make stationTableReader code more reusable

src/commonMain/kotlin/au/id/micolous/metrodroid/card/nfcv/NFCVCard.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/ultralight/UltralightCard.kt
Collapsing is useful when a single entry is long enough but ultralight/NFCV
pages are only 4 bytes. Collapsing them only makes it more difficult to see
around
=> ultralight, nfcv: drop collapsing values

src/main/res/layout/subscription_item.xml
Some subscription name end up too long for a single line, allow it to
overflow
=> subscription_item: Allow subscription name to span several lines

src/androidTest/java/au/id/micolous/metrodroid/test/ExportHelperTest.kt, src/jvmCommonMain/kotlin/au/id/micolous/metrodroid/serializers/XmlOrJsonFormat.kt
ZipIterator is clumsy, large and difficult to read. Instead replace it
by way simpler direct iteration logic
=> XmlOrJsonFormat: Simplify ZIP handling

src/commonMain/kotlin/au/id/micolous/metrodroid/transit/en1545/En1545FixedInteger.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/en1545/En1545Parsed.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/en1545/En1545TransitData.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/intercode/IntercodeTransitData.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/lisboaviva/LisboaVivaTransitData.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/mobib/MobibTransitData.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/opus/OpusTransitData.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/ovc/OVChipTransitData.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/pisa/PisaTransitData.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/ravkav/RavKavTransitData.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/ricaricami/RicaricaMiTransitData.kt
This is an alternative to #497.
* New `bcdDate` field naming for EN1545.
* Renames `En1545FixedInteger` methods `parseBCDDate` and `BCDdate` to `parseDateBCD` and `dateBCD` respectively for consistency (with `datePacked`, etc.)
* Hide holders' date of birth and postal code when hideCardNumbers or obfuscateTripDates are enabled (similar to `MobibTransitData` behaviour).
* Rename `HOLDER_POSTAL_CODE` to `HOLDER_INT_POSTAL_CODE` to clarify datatype.
Presently, this is only used by Mobib (Belgium), which has 4 digit postal codes from 1000-9999, but may be an issue if other cards start using the field.
* Removes reference to `HOLDER_POSTAL_CODE` in `IntercodeTransitData` -- only Mobib uses it, and `MobibTransitData`, which is not based on the Intercode classes.
* Mark all `HOLDER_BIRTH_DATE` …
=> Remove En1545Parsed.getTimeStampString, and clean up En1545TransitData.info

src/androidTest/java/au/id/micolous/metrodroid/test/BaseInstrumentedTestPlatform.kt, src/androidTest/java/au/id/micolous/metrodroid/test/TransitCurrencyTest.kt, src/main/java/au/id/micolous/metrodroid/transit/TransitCurrency.kt
Our current spans do not conform to specification. As a result the currency is
not read at all which is bad. Fix our spans
=> TransitCurrency: Fix TTS spans

build.gradle, jvmcli/build.gradle, src/androidTest/java/au/id/micolous/metrodroid/test/BaseInstrumentedTestPlatform.kt, src/androidTest/java/au/id/micolous/metrodroid/test/TransitCurrencyTest.kt, src/androidTest/kotlin/au/id/micolous/metrodroid/test/TransitCurrencyTest.kt, src/androidUnitTest/kotlin/au/id/micolous/metrodroid/test/BaseInstrumentedTestPlatform.kt, src/main/java/au/id/micolous/metrodroid/transit/TransitCurrency.kt
Robolectric formatting is worse than android but is overall acceptable. Accept it only when running as unit test
=> Make TransitCurrencyTest run as unit test as well

src/commonMain/kotlin/au/id/micolous/metrodroid/transit/TransactionTrip.kt
No strong reason. Just feels cleaner
=> TransactionTrip: Move fare from abstract to concrete class

src/commonTest/kotlin/au/id/micolous/metrodroid/test/OctopusTest.kt
It's more representative of real flow
=> OctopusTest: run test methods on card rather than FelicaCard

proto/build.gradle
Missing bytecode level made the compiler default to highest level which made
android tools choke
=> proto: Fix compilation error with Java 12

.travis.yml, .travis/jvmcli_test.sh, README.md, jvmcli/README.md, jvmcli/build.gradle
* Add documentation with worked examples for `jvmCli`
* Use Shadow's application plugin for `jvmCli`
* Build `jvmCli` hermetically
* Adds a script into the Travis configuration to run `jvmCli` with basic integration test on Opal data
* Adds a note that ZIP downloads won't work
=> Add tests and documentation for `jvmcli`.

native/metrodroid/metrodroid/NFCReader.swift, native/metrodroid/metrodroid/SupportedCardsViewController.swift, src/commonMain/kotlin/au/id/micolous/metrodroid/card/Card.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/CardType.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/ClassicAuthenticator.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/ClassicCard.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/ClassicCardFactoryRegistry.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/ClassicCardTech.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/ClassicReader.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/MifarePlusWrapper.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/classic/PlusProtocol.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/key/CardKeysFromFiles.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/key/ClassicCardKeys.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/key/ClassicKeysImpl.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/key/ClassicSectorKey.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/umarsh/UmarshTransitData.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/unknown/UnauthorizedClassicTransitData.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/util/Aes.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/util/Cmac.kt, src/commonTest/kotlin/au/id/micolous/metrodroid/test/ClassicReaderTest.kt, src/commonTest/kotlin/au/id/micolous/metrodroid/test/VirtualClassic.kt, src/iOSMain/kotlin/au/id/micolous/metrodroid/card/classic/PlusCardReaderIOS.kt, src/iOSMain/kotlin/au/id/micolous/metrodroid/util/Aes.kt, src/jvmCommonMain/kotlin/au/id/micolous/metrodroid/util/Aes.kt, src/main/java/au/id/micolous/metrodroid/card/AndroidCardTransceiver.kt, src/main/java/au/id/micolous/metrodroid/card/CardReader.kt, src/main/java/au/id/micolous/metrodroid/card/classic/ClassicAndroidReader.kt, src/main/java/au/id/micolous/metrodroid/card/classic/ClassicCardTechAndroid.kt, src/main/res/values/strings.xml
Since Mifare plus is essentially a Mifare Classic with a longer key.
It's even possible for some sectors to be in classic and some other in plus mode
This patch treats it as a variant of mifare classic
The transit factory list is split to avoid needlessly iterating through wrong
factories but one factory may be in both lists.
=> Support reading Mifare Plus

src/commonMain/kotlin/au/id/micolous/metrodroid/transit/en1545/En1545FixedInteger.kt, src/commonTest/kotlin/au/id/micolous/metrodroid/test/En1545Test.kt
Fix an issue where a `date of birth` field being present but set to 0 would cause an array-out-of-bounds in `Timestamp.YMD`.
(bug introduced in #569)
=> en1545: Fix null date of birth

src/main/java/au/id/micolous/metrodroid/multi/FormattedString.kt
[`TypefaceSpan.getTypeface()` is only available on API 28](https://developer.android.com/reference/android/text/style/TypefaceSpan.html?hl=en#getTypeface()).
I don't think we ever actually use the `typeface` parameter -- and I'm not sure if it is non-null if we set `fontFamily` instead.
=> Fix possible crash with TypefaceSpan on pre-P devices

native/metrodroid/metrodroid/Assets.xcassets/collapsed_header.imageset/Contents.json
In RTL languages the arrow ends up pointing towards the
string rather than away. So mark it as needing a flip on
RTL languages.
Android is not affected due to different design
=> collapsed_header: Flip on RTL layouts

src/commonMain/kotlin/au/id/micolous/metrodroid/time/Timestamp.kt
We don't really care about handling them correctly,
especially given that before 1600 in Western Europe and
1918 in Russia there are several correct ways of handling
dates involving Julian calendar. At least we shouldn't crash
This code implements proleptic astronomical Gregorian calendar
that is the easiest to implement with just few fixes even though
this is not customary used by historians.
=> Fix crash when handling BCE dates

native/metrodroid/metrodroid/Info.plist
I was under mistaken impression that document picker didn't exist on iOS.
Hence I registered Metrodroid as a reader for zip and json. As
document picker does exist and now we use it and we're not a real viewer for
either of formats, it is probably better not to pollute "share with" selection
and that decreases probability that someone tries to open unrelated zip or
unrelated json with us leading to unexpected results.
This also makes it closes to Android
=> iOS: Remove metrodroid registration as "Open with" target

build.gradle, jvmcli/build.gradle, proto/build.gradle
Update some dependencies, and make versioning consistent again:
* Kotlin 1.3.11 (jvmcli) / 1.3.41 (others) ▶️ ~1.3.50~ 1.3.41 (consistently)
* Android Gradle Plugin 3.2.1 (jvmcli) / 3.4.1 (others) ▶️ 3.4.1 (consistently)
* Protobuf 3.0.1 ▶️ 3.9.1 (consistently); [switched to new JavaLite configuration style used in Protobuf 3.8.0+](https://github.com/google/protobuf-gradle-plugin#default-outputs)
* Protobuf Gradle Plugin 0.8.6 (jvmcli) / 0.8.8 (others) ▶️ 0.8.10 (consistently)
Removes duplicated definitions of `buildscript.ext` in `jvmcli/build.gradle`.
Some stuff here is still behind the current version -- the key things I was going for was making `jvmcli/build.gradle` consistent, and getting [one of the illegal reflective access …
=> roll forward dependency versions; externalise some dep versions

src/commonMain/kotlin/au/id/micolous/metrodroid/time/Timestamp.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/octopus/OctopusData.kt, src/commonTest/kotlin/au/id/micolous/metrodroid/test/OctopusTest.kt
This was 2017-11-01 before, when it should actually be 2017-10-01.
This also adds a `Month` enum to `Timestamp`, to make it easier to avoid this issue.
=> octopus: Fix transition date; add month enum

src/main/res/layout/activity_main.xml
There was a linter warning advising about a useless RelativeLayout and/or LinearLayout.  Before 48546934721182565dd4726545f640c0481d6ebc, this was Linear -> Relative -> Linear.  48546934721182565dd4726545f640c0481d6ebc changed this to just Linear, but it moves all the UI elements to the top of the screen.
This partially reverts the commit, such that it only has Relative -> Linear, add disables the linter warning.  That way, all the UI elements are centred again.
=> Fix-up MainActivity layout regression.

src/main/java/au/id/micolous/metrodroid/fragment/CardsFragment.kt, src/main/java/au/id/micolous/metrodroid/fragment/KeysFragment.kt, src/main/java/au/id/micolous/metrodroid/util/Utils.kt
We have 2 different way of handling import on pre-Kitkat:
1. Use hardcoded file name (cards import)
2. Use an intent but different than post-Kitkat one (key import)
So let's settle on one: an intent and merge the code.
I tested it on my Blackberry Q10 that implements android 4.3 VM.
=> Change file import to use the same code as key import on pre-Kitkat

src/main/java/au/id/micolous/metrodroid/fragment/CardBalanceFragment.kt, src/main/java/au/id/micolous/metrodroid/fragment/SupportedCardsFragment.kt, src/main/java/au/id/micolous/metrodroid/util/Utils.kt
Experience shows that rendering supported card view is especially crash-prone
on older devices. Add a safety net to show an error rather than crash outright.
While on it extract view reuse logic into a separate function
=> Stretch a safety net under rendering of supported card

src/main/java/au/id/micolous/metrodroid/fragment/CardsFragment.kt
It's only used on pre-KitKat, so the deprecation warning is irrelevant
=> CardsFragment: Supress deprecation warning in pre-KitKat code

.travis.yml
There have been a few of these lately:
* #650: https://travis-ci.org/metrodroid/metrodroid/jobs/593850496
* #661: https://travis-ci.org/metrodroid/metrodroid/jobs/593925575
* #665: https://travis-ci.org/metrodroid/metrodroid/jobs/593955677
To try to improve the situation, this clamps JVM memory use to 1.5GB, MetaspaceSize to 0.75GB and dumps the heap on OOM.  Travis has a 4GB limit.
This only applies to use on Travis.
=> travis: limit JVM to 1.5G RAM

src/iOSMain/kotlin/au/id/micolous/metrodroid/time/Timestamp.kt
#647 changed the way `getMonth` works.  This fixes the use on iOS.
=> ios: fix getMonth usage after PR#647

.travis.yml, build.gradle, gradle.properties
Addresses this warning:
```
WARNING: DSL element 'useProguard' is obsolete and will be removed soon.
Use 'android.enableR8' in gradle.properties to switch between R8 and Proguard.
```
To be applied after #670
=> r8: Use non-deprecated flags

extra/mdst/csv2pb.py, extra/mdst/mdst.py
The `Station` and `Operator` code is already in `mdst.py`, may as well move the `Line` code there too.
I intend to use this #675
=> csv2pb: add "mode" column to Lines, move Line code to mdst.py

native/metrodroid/metrodroid/Info.plist, src/iOSMain/kotlin/au/id/micolous/metrodroid/time/Timestamp.kt
This is built on #672, because the build is broken without it.
This prevents Metrodroid being offered on hardware that doesn't support CoreNFC (eg: iPhone 6; iPad).
Device/Capabilities matrix here: https://developer.apple.com/support/required-device-capabilities/
=> ios: Require nfc hardware

src/main/res/values-el/strings.xml
There are essentially 3 ways of doing it
1. Keep it in English
2. Phonetically. Closest phonetically would be "Μετροντροιντ"
3. Go back to original "android" (human-like robot) word "ανδροειδ"
and replace "an" with "Metro" ("Μετρό").
This patch uses the third variant
=> Add Greek spelling of Metrodroid

build.gradle
We don't appear to use Apache Commons in `jvmCliMain` directly.  This removes those dependencies.
(Split off from #600)
=> jvmCliMain: remove unused deps

docs/ios.md, native/metrodroid/metrodroid/SupportedCardsViewCell.swift, src/commonMain/kotlin/au/id/micolous/metrodroid/card/felica/FelicaCard.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/felica/FelicaReader.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/felica/FelicaService.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/felica/FelicaSystem.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/CardInfo.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/octopus/OctopusTransitData.kt, src/commonTest/assets/felica/felica-empty-system.json, src/commonTest/assets/felica/felica-skipped-service.json, src/commonTest/assets/felica/felica-skipped-system-missing-services.json, src/commonTest/assets/felica/felica-skipped-system.json, src/commonTest/kotlin/au/id/micolous/metrodroid/test/FelicaJsonImportTest.kt, src/iOSMain/kotlin/au/id/micolous/metrodroid/card/felica/FelicaCardReaderIOS.kt, src/jvmCommonTest/kotlin/au/id/micolous/metrodroid/test/FelicaXmlImportTest.kt, src/main/java/au/id/micolous/metrodroid/activity/MainActivity.kt, src/main/java/au/id/micolous/metrodroid/card/CardReader.kt, src/main/java/au/id/micolous/metrodroid/util/Preferences.kt, src/main/res/values/strings.xml, src/main/res/xml/prefs.xml
This is on top of #672; as iOS version doesn't build without that patch.
This adds a new parameter to `FelicaReader.dumpTag`, `onlyFirst`.  When `onlyFirst = true`, any system codes after `index 0` will be skipped, an empty `FelicaService` is inserted in place, and the event is logged.
* On Android, there is a new developer option to toggle this setting. I didn't put it in "NFC Preferences" because this should only be used for debugging and development.
* On iOS, `onlyFirst` is hard coded to `true` to work around #613.
This will probably only read the Octopus part of Hu Tong Xing (互通行).  I don't have a sample to test with this for sure, but I think this will only fully work once the underlying bug in iOS is fixed.
I tested this with these single-system cards (which work already, and also …
=> ios: Workaround for reading multi-system FeliCa cards (issue #613)

extra/mct_to_mfcdump.py
This is what `MctCardImporter` does.
This is needed when you have a dump from MCT where Key B was unknown or unreadable, eg:
`A1A2A3A4A5A678778869------------`
=> mct_to_mfcdump.py: add null bytes when bytes are unknown

data/Makefile
On some systems GNU make is not called make, e.g gmake on FreeBSD.
=> Use $(MAKE) instead of plain make.

jvmcli/windows.md
I think this is a slightly more sensible solution, but [Unicode in Java on Windows has been broken for 21 years](https://bugs.openjdk.java.net/browse/JDK-4153167). 😞
=> Docs for broken java/windows unicode stuff

src/commonMain/kotlin/au/id/micolous/metrodroid/transit/clipper/ClipperTrip.kt, src/commonTest/kotlin/au/id/micolous/metrodroid/test/ClipperTest.kt
Historically, Muni just stored a 4-digit (decimal) vehicle number as part of a
Trip record on the Clipper Card. Muni rolled out a line of new LRV4 Light Rail
cars a while ago with newer Clipper Card readers. These readers also store
which car you are in (A vs B) for multi-car trains, in addition to the 4-digit
vehicle number, but as an extra decimal digit at the end, mapping 0d1 => A, 0d2
=> B, etc. For example, vehicle number 2046A is stored as 0d20461 (0x3fed),
2046B is stored as 0d20462 (0x4fee), etc.
This change modifies the ClipperTrip vehicleID method to take this into account
and adds some tests for it along the way.
The Trip rows come from an actual Clipper card that I've been using.
=> Clipper: Fix vehicle numbers for LRV4 Muni Vehicles

.travis/start_android_emulator.sh
Google Emulator 29.2.11 made some changes to their CLI API. From
https://androidstudio.googleblog.com/2019/12/emulator-29211-and-amd-hypervisor-12-to.html
> The binary emulator-headless is now retired. Headless builds of the engine
> are now launched via emulator -no-window, thus unifying the previously
> separate (but similar) paths.
This change modifies one of the Travis CI scripts to pick up this change. I
tested this on my private Travis CI build and it seemed to fix things.
=> Fix Travis CI builds

.travis.yml
This should ensure that F-Droid builds cleanly even if `third_party/protobuf` has been deleted.
Context: https://github.com/metrodroid/metrodroid/issues/640#issuecomment-574491810
=> Add a CI target which deletes protobuf

src/commonMain/kotlin/au/id/micolous/metrodroid/transit/seq_go/SeqGoData.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/seq_go/SeqGoTrip.kt
* Uses agency name from mDST
* Refactor "Airtrain" code to be minimal for handling their stations
=> seq_go: Use agency names from mdst (except Airtrain)

src/commonMain/kotlin/au/id/micolous/metrodroid/card/felica/FelicaCard.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/felica/FelicaConsts.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/felica/FelicaProtocol.kt, src/commonMain/kotlin/au/id/micolous/metrodroid/card/felica/FelicaReader.kt, src/commonTest/assets/felica/felica-spec-version-aes-only.json, src/commonTest/assets/felica/felica-spec-version-des.json, src/commonTest/kotlin/au/id/micolous/metrodroid/test/FelicaJsonImportTest.kt, src/jvmCliMain/kotlin/au/id/micolous/metrodroid/card/JavaCardTransceiver.kt, src/main/res/values/strings.xml
For FeliCa as part of dumping process, this change sends a `Request Specification Version` command. This contains the FeliCa specification version that a card supports, and also indicates whether a card supports DES (no `option versions` = no DES).
I've tested this with various Japanese IC cards -- the only "weirdness" was that my PASMO does not respond to it at all; so I wrapped up the `CardLostException` (similar to a number of other fallback mechanisms we use on FeliCa).
I added support for propagating up `CardLostException` from `JavaFelicaTransceiver`, which was needed to read the PASMO correctly with the ACR122.  This class already hard codes a bunch of ACR122/PN532-specific code (using ACR122 `Escape` + PN532 `InDataExchange`); I've got already got another branch starting to …
=> felica: Add Request Specification Version, show raw response and PMm on raw data view

extra/mdst/compile_stops_from_gtfs.py, extra/mdst/mdst.py
Git becomes a lot more useful when files don't change randomly as the result of a build.
It looks like this was intended in cc115941a27c7a55bb57892044fade17252e5bb0, but protobuf was still free to serialize maps however it saw fit.
=> Deterministically serialize the MdST

src/commonMain/kotlin/au/id/micolous/metrodroid/transit/clipper/ClipperTrip.kt
This change fixes the "Unresolved reference: Integer" error that robbiet480
discovered in https://github.com/metrodroid/metrodroid/pull/715.
=> Clipper: Remove Integer reference

src/commonMain/kotlin/au/id/micolous/metrodroid/transit/amiibo/AmiiboTransitFactory.kt
According to https://www.3dbrew.org/wiki/Amiibo#Page_layout, page 0x4
* always starts with 0xA5
* remaining bytes are initially all-zero
I read this as "and", but it's probably "and/or": #718 has a dump of a Amiibo that I suspect has never been written to by Nintendo hardware/software.
Before:
```
% ./metrodroid-cli parse ~/dev/cards/amiibo/green-yoshi-nvl-201.json
card UID = <04138f9a844981>
name = null
serial = null
```
After:
```
% ./metrodroid-cli parse ~/dev/cards/amiibo/green-yoshi-nvl-201.json
card UID = <04138f9a844981>
name = Amiibo
serial = null
info
Type: Yarn
Character: Yoshi [0x3]
Character variant: 1
Model number: 65
Series: Yoshi's Woolly World
```
=> Fix #718: Support Amiibos that have never been written to

.gitmodules, build.gradle, settings.gradle, src/jvmCliMain/kotlin/au/id/micolous/metrodroid/card/JavaCardTransceiver.kt, src/jvmCliMain/kotlin/au/id/micolous/metrodroid/cli/SmartCard.kt
This allows us more direct control with the PC/SC API, rather than being stuck with the limitations of the `java.smartcardio` API.  It will also eventually allow a native target to eventually use the PC/SC API (but this isn't implemented here).
This replaces the dependencies on `openjavacard-smartcardio` and `jnasmartcardio` with `kotlin-pcsc` ([a library that I built for this purpose](https://github.com/micolous/kotlin-pcsc)).
=> jvmcli: Migrate from smartcardio to kotlin-pcsc

build.gradle, src/main/res/layout/activity_about.xml, src/main/res/layout/activity_license.xml, src/main/res/layout/activity_main.xml, src/main/res/layout/subscription_item.xml, src/main/res/values/attrs.xml, src/main/res/values/themes.xml, src/main/res/xml/prefs.xml
This fixes issues when Android is set to use the largest font and display sizes (fixes #744):
* 203a5f7289232a51dd39d01788320d63e08db990: always use multi-line labels for titles of preferences (which is also a problem for German at default font size)
* 482b0cb907bb5f92f027a03109d997709a0ed15e: wrap the About screen in a `ScrollView`
* 3bac09cd346e88e522b8b91ff7dd90c14b0dc268: move License screen's padding from the `ScrollView` to the `TextView`, so it has a larger viewport
* 6d35f303aa1fdfd74bca2acfc6789dd07f843c56: show full subscription names at large font sizes
Screenshots here: https://github.com/metrodroid/metrodroid/issues/744#issuecomment-752826115
Rebasing on #662 (Material Design).
=> Fix large font layout issues on Android

build.gradle, native/metrodroid/metrodroid.xcodeproj/project.pbxproj, src/iOSMain/cinterop/stations.def, src/iOSMain/kotlin/au/id/micolous/metrodroid/util/StationTableReader.kt
* Roll forward to Kotlin 1.3.50
* Fix a build issue for the iOS Simulator target.  Building for iOS devices is still broken (#747).
* Automated project updates from Xcode 12.3
=> Kotlin 1.3.50

data/opus/rtc.xml, data/opus/rtl.xml, data/opus/stl.xml, data/opus/stm.xml, extra/mdst/xml2pb-opus.py, src/commonMain/kotlin/au/id/micolous/metrodroid/transit/opus/OpusLookup.kt
**Edit:** Forgot to mention that all ticket types below are STM ones. I don't know if other agencies have different codes.
Namely:
* Correct transport modes. STM run buses and metros, not buses and trains. Commuter rail lines will now be handled as trains instead.
* Ticket type 201 is also weekly subscription.
* Updated the XML files. Those are pulled from https://github.com/tral/LecteurOPUS which is the continuing fork of the original repository. Author is credited. cc. @tral 
Things that I have not included in the PR but you can consider:
* Ticket type 2060 is 10-trip.
* Ticket type 923 is 2-trip.
* Ticket type 1195 is *OPUS à l'essai*. Various transport agencies give away to drivers OPUS cards loaded with 10-trip fares (with shortened validity, which the app correctly interprets). This …
=> Québec OPUS card fixes

src/main/java/au/id/micolous/metrodroid/activity/CardInfoActivity.kt, src/main/java/au/id/micolous/metrodroid/fragment/CardsFragment.kt, src/main/java/au/id/micolous/metrodroid/fragment/KeysFragment.kt, src/main/java/au/id/micolous/metrodroid/key/CardKeysDB.kt, src/main/java/au/id/micolous/metrodroid/util/ExportHelper.kt
When there is no column we will get a throw anyway. Getting a throw earlier is
a benefit for debugging. But we should never get into this situation as we
control our DB
=> Use getColumnIndexOrThrow instead of getColumnIndex

src/jvmCommonMain/kotlin/au/id/micolous/metrodroid/serializers/NodeWrapperImpl.kt, src/jvmCommonMain/kotlin/au/id/micolous/metrodroid/serializers/XmlOrJsonFormat.kt, src/jvmCommonMain/kotlin/au/id/micolous/metrodroid/serializers/XmlPullParserIterator.kt
All callers derive InputStream as ByteArrayInputStream from a String.
Let's reduce back-and-forth between String (UTF-16) and ByteArray(UTF-8).
=> NodeWrapperImpl: work on String rather than InputStream

src/commonMain/kotlin/au/id/micolous/metrodroid/transit/china/ChinaTransitData.kt
With 2 known working TUNION cards(one known working on an older version of metrodroid), the latest code only recognizes SFI files(ISO7816), which are sufficient to retrieve card info. Old reader code will somehow generate some duplicated standard file data entries, so it wasn't broken.
This patch add SFI file as fallback to fix TUNION reader on latest version. I didn't replace everything because I only have TUNION cards to verify while multiple card variants share the same code.
=> fix TUNION card reader by adding sfi file as fallback

src/commonMain/kotlin/au/id/micolous/metrodroid/transit/clipper/ClipperTrip.kt
My Clipper card has a few different transit codes for Caltrain and Munin rides
=> Update some Caltrain and Muni mode icons

src/commonMain/kotlin/au/id/micolous/metrodroid/transit/tfi_leap/LeapUnlocker.kt
Update Leapcard API URL
Current URL no longer works - it points to the same API but certificate does not include tnfc.leapcard.ie and as expected unlocking does not work. With this URL I was once again able to unlock Leapcards.
=> Update Leapcard API URL

README.md
Hello,
Mobib card are used in whole Belgium.
I live in Wallonia, so I own a TEC Card recognized by the software. So I removed Brussel as the app is ready for the whole Belgium
=> Update README.md | Mobib
